# Generated by Django 6.0 on 2026-04-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_alter_category_status_alter_pantryitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='min_threshold',
            field=models.PositiveIntegerField(default=1, help_text='Notify when quantity drops below this.'),
        ),
    ]
