# Generated by Django 6.0 on 2026-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_pantryitem_min_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='unit',
            field=models.CharField(choices=[('count', 'Count'), ('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds'), ('oz', 'Ounces'), ('l', 'Liters'), ('ml', 'Milliliters')], default='count', max_length=10),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='min_threshold',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Notify when quantity drops below this.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current quantity in the pantry.', max_digits=10),
        ),
    ]
