# Generated by Django 6.0 on 2026-04-19 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='pantry_item_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredients', to='pantry.pantryitem'),
        ),
    ]
