# Generated by Django 6.0 on 2026-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_alter_grocerytrip_status_alter_purchaseditem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='quantity_bought',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
